### ISSUE TITLE
Create RC.2

### ISSUE THREAD

**Issue by zepumph** [phetsims/ratio-and-proportion#337]
To Cherrypick:

- [x] https://github.com/phetsims/scenery/commit/40eca0b26f0e394be8a6db601effff067dea0a71 from https://github.com/phetsims/scenery/issues/1147
- [x] COmmits in https://github.com/phetsims/ratio-and-proportion/issues/341
- [x] COmmit in https://github.com/phetsims/ratio-and-proportion/issues/342 already cherry picked, just needs QA confirm
- [x] https://github.com/phetsims/ratio-and-proportion/issues/346 already ready for QA, nothing to cherry pick
- [x] https://github.com/phetsims/ratio-and-proportion/issues/347 already cherry picked, nothing for QA to confirm
- [x] note https://github.com/phetsims/ratio-and-proportion/issues/285
- [x] https://github.com/phetsims/ratio-and-proportion/issues/301
- [x] https://github.com/phetsims/ratio-and-proportion/issues/321
- [x] https://github.com/phetsims/QA/issues/601#issuecomment-777986115
- [x] https://github.com/phetsims/utterance-queue/commit/8104d517b9720d5111e9e2e453f0010c9fa188af from https://github.com/phetsims/ratio-and-proportion/issues/348
- [x] https://github.com/phetsims/joist/issues/682

**Comment by zepumph** [comment]
- [ ] https://github.com/phetsims/ratio-and-proportion/issues/345, please note that QA should confirm fixed, but this is still out for a design review, so don't close.
- [ ] https://github.com/phetsims/ratio-and-proportion/issues/341

**Comment by zepumph** [comment]
Everything has been cherry picked into the branch. I'll proceed with a new one.

**Comment by zepumph** [comment]
RC complete, see https://github.com/phetsims/QA/issues/609
